version: "3.9"

services:
  app:
    container_name: browse-partners-app
    image: browse-partners-app
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000